[project]
name = "bertani"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "belatijagad", email = "belatijagadbintangsyuhada@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "kaggle>=2.2.4",
    "kaggle-environments>=1.32.7",
]

[project.scripts]
bertani = "bertani:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
